# Generated by Django 4.2 on 2023-04-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_article_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Friends',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='Surname',
            new_name='Name',
        ),
    ]
