# Generated by Django 4.2 on 2023-04-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_rename_author_friends_rename_surname_friends_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='MyProfile',
            name='Friends',
        ),
        migrations.AddField(
            model_name='MyProfile',
            name='friends',
            field=models.ManyToManyField(to='UserProfile.friends'),
        ),
    ]
