# Generated by Django 4.2 on 2023-05-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_remove_article_friends_article_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='Name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='Name',
        ),
        migrations.AddField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
